from random import random
print('~' * 30)
print('MENOR E MAIOR VALORES EM TUPLA')
print('~' * 30)
a = round(random() * 100)
b = round(random() * 100)
c = round(random() * 100)
d = round(random() * 100)
e = round(random() * 100)
sorteio = (a, b, c, d, e)
print(f'Os números sorteados foram: {sorteio}')
print('-' * 30)
print(f'O menor número sorteado foi: {min(sorteio)}')
print('-' * 30)
print(f'O maior número sorteado foi: {max(sorteio)}')
print('-' * 30)
print(f'A soma de todos os valores da tupla é igual a {sum(sorteio)}')
